// Tangled @ 2025-07-07T22:45:53-04:00 - DO NOT EDIT!
// Source: /home/brandt/Projects/Repos/umbrella/packages/fibers/tpl.readme.md

import { fiber, wait } from "@thi.ng/fibers";
import { ConsoleLogger } from "@thi.ng/logger";

// wrap an endless generator as fiber
const app = fiber(
	function* () {
		while(true) {
			console.log("hello");
			// wait 0.25s
			yield* wait(250);
			console.log("fiber");
			// wait 1s
			yield* wait(1000);
		}
	}
);

// start processing it with default handlers
// see: https://docs.thi.ng/umbrella/fibers/classes/Fiber.html#run
app.run();

// create a child process which runs semi-independently
// (only executes if parent is still active)
// child fibers are auto-removed from parent when they terminate
const child = app.fork(
	// the `ctx` arg is the fiber wrapping this generator
	function* (ctx) {
		for(let i = 0; i < 3; i++) {
			ctx.logger?.debug("count", i);
			yield* wait(100);
		}
		// return value will be stored in fiber for future reference
		return 42;
	},
	// fiber options
	{
		// custom fiber ID (else autogenerated)
		id: "child-demo",
		// custom logger (default: none)
		logger: new ConsoleLogger("child")
	}
);

// hello
// [DEBUG] child: init child-demo
// [DEBUG] child: count 0
// [DEBUG] child: count 1
// [DEBUG] child: count 2
// fiber
// [DEBUG] child: done child-demo 42
// [DEBUG] child: deinit child-demo
// hello
// fiber
// hello
// ...

// once a fiber has completed, its value can be obtained
// e.g. here we create another fiber, which first waits for `child` to complete
app.fork(function* () {
	// wait for other fiber
	const result = yield* child;
	console.log("result", result);
	// alt way to obtain value
	console.log("deref", child.deref());
});
// result 42
// deref 42